name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.0

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run unit tests
      run: make test

    - name: Run integration tests
      run: make integration-test
